[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y pkg-config libssl-dev curl unzip",
    "curl -sSL https://github.com/protocolbuffers/protobuf/releases/download/v24.3/protoc-24.3-linux-x86_64.zip -o protoc.zip",
    "unzip protoc.zip -d /usr/local",
    "chmod +x /usr/local/bin/protoc"
]
