name: Checks

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: warp-ubuntu-latest-x64-16x
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Run WarpBuilds/rust-cache
        uses: WarpBuilds/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run sccache-action
        uses: mozilla-actions/sccache-action@v0.0.5

      - name: Set sccache env vars
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Install native dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - run: make lint
      - run: make test
